services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: verdie
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: ['redis-server', '--protected-mode', 'no']

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
