services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: verdie
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: ['redis-server', '--protected-mode', 'no']

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-container
    ports:
      - '5540:5540'
    volumes:
      - redisinsight-data:/data

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  redisinsight-data:
    driver: local
